### PR TITLE
Move old site to /ARCHIVE and add new Svelte site

### PR DESCRIPTION
**Pull request by erskingardner**
image

## Stuff that's done: 
- [x] Desktop layout
- [x] Mobile layout
- [x] Home page (without member list or conversation, see below)
- [x] Join page (without conversation, see below)
- [x] Language switcher
- [x] i18n for all content added so far
- [x] New favicon

## Stuff still left to do:

- [x] Add Nostr conversation thread to the `/` and `/join` pages (using NDK?)
- [x] Add member list to the `/` page

### CODE REVIEW

**Comment by erskingardner** [comment]
@gazhayes @pqingshuang New site using Svelte! 🤙🏼 There is still some Nostr stuff to add so think we should just keep working on this branch/PR until that's done too.

**Comment by gsovereignty** [comment]
Nice work!

Haven't looked but do you have a build script in there to build a static site that can be served with github pages?

**Comment by gsovereignty** [comment]
> There is still some Nostr stuff to add

NDK probably the better option but I'm guessing it might still have breaking changes

**Comment by erskingardner** [comment]
@gazhayes There isn't a build script and I don't know if we can reduce it to a static site. The easiest way to run svelte sites (for free) is to use Vercel. I need to add an adapter but then you get build and deploy on merge to the master/main branch and you can even add some analytics easily.

I've added NDK, we can keep an eye on it but the current version is working well with what we need. I can't change under us since Pablo is releasing to npm. 

The site is now ready I think.

**Comment by erskingardner** [comment]
Ok – I've just added the vercel adapters so if you want to go that route you can simply: 
1. Create an account on Vercel.
2. Merge this PR.
3. Connect this repo on a new project in Vercel.
4. It'll build immediately to a temp domain.
5. You can easily add the nostr.hk domain to the project with a quick CNAME change and then it'll just start working.

**Comment by shaibearary** [comment]
@erskingardner Hi Jeff thanks for your work. I noticed there is missing event if it reply to a event replying to root. I will take a look at this, if you have time i think you will do it faster haha

**Comment by erskingardner** [comment]
@pqingshuang – I'm not sure I understand the issue, is it that you're seeing an event (a reply) somewhere else that isn't showing in the thread or replies on the site? Happy to look into it, just need to understand better.

**Comment by shaibearary** [comment]
@erskingardner 
Exactly, please see the screenshot below and see the differenceimage

image

I console log all events and it contains everything in the thread so the logic in the function below might be buggy
https://github.com/nostrocket/nostr.hk/blob/c4d064e888bfab7da82bb44f574d85fab4c841f1/src/lib/utils.ts#L32

This could be a reference 
https://github.com/nostrocket/nostr.hk/blob/887d4d31f3b79be1d88570f82174afddcbf04776/comments.js#L63-L100

**Comment by erskingardner** [comment]
Ah ok. Im pretty sure I know what’s happening. My recursive function isn’t as recursive as it should be. I’ll take a look.

**Comment by shaibearary** [comment]
i think the thread problem fixed now ~
BTW @erskingardner in the main page i see you use threadUrl, damusUrl etc, kind feel it should be replaced by some links right?

**Comment by gsovereignty** [comment]
Turns out you need Vercel pro account to deploy anything from an organization.

@pqingshuang @erskingardner if you get a chance maybe you could try this (I can do it but not till later in the week): https://kit.svelte.dev/docs/adapter-static

If it works we can just deploy to github pages.

**Comment by shaibearary** [comment]
https://pqingshuang.github.io/nostr.hk/ Check here. I think we are ready. I will make build process automaticlly later today

**Comment by gsovereignty** [comment]
Hey @pqingshuang the new site is working, so does that mean this doesn't need to be merged?

**Comment by shaibearary** [comment]
it still needs, i added the current git page to this branch to test and currently looks fine, I will merge it to main tonight

**Pull request merged**
